PRODUCT_COPY_FILES += \
    vendor/zte/nx503a/gapps/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh \
    vendor/zte/nx503a/gapps/addon.d/71-gapps-faceunlock.sh:system/addon.d/71-gapps-faceunlock.sh \
    vendor/zte/nx503a/gapps/app/Books.apk:system/app/Books.apk \
    vendor/zte/nx503a/gapps/app/FaceLock.apk:system/app/FaceLock.apk \
    vendor/zte/nx503a/gapps/app/GenieWidget.apk:system/app/GenieWidget.apk \
    vendor/zte/nx503a/gapps/app/Gmail2.apk:system/app/Gmail2.apk \
    vendor/zte/nx503a/gapps/app/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter.apk \
    vendor/zte/nx503a/gapps/app/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk \
    vendor/zte/nx503a/gapps/app/GoogleEars.apk:system/app/GoogleEars.apk \
    vendor/zte/nx503a/gapps/app/GoogleTTS.apk:system/app/GoogleTTS.apk \
    vendor/zte/nx503a/gapps/app/Hangouts.apk:system/app/Hangouts.apk \
    vendor/zte/nx503a/gapps/app/Magazines.apk:system/app/Magazines.apk \
    vendor/zte/nx503a/gapps/app/Maps.apk:system/app/Maps.apk \
    vendor/zte/nx503a/gapps/app/MediaUploader.apk:system/app/MediaUploader.apk \
    vendor/zte/nx503a/gapps/app/Music2.apk:system/app/Music2.apk \
    vendor/zte/nx503a/gapps/app/PlayGames.apk:system/app/PlayGames.apk \
    vendor/zte/nx503a/gapps/app/PlusOne.apk:system/app/PlusOne.apk \
    vendor/zte/nx503a/gapps/app/Street.apk:system/app/Street.apk \
    vendor/zte/nx503a/gapps/app/Videos.apk:system/app/Videos.apk \
    vendor/zte/nx503a/gapps/app/YouTube.apk:system/app/YouTube.apk \
    vendor/zte/nx503a/gapps/etc/g.prop:system/etc/g.prop \
    vendor/zte/nx503a/gapps/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/zte/nx503a/gapps/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/zte/nx503a/gapps/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/zte/nx503a/gapps/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/zte/nx503a/gapps/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
    vendor/zte/nx503a/gapps/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/zte/nx503a/gapps/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/zte/nx503a/gapps/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/zte/nx503a/gapps/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so \
    vendor/zte/nx503a/gapps/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/zte/nx503a/gapps/lib/libcrashreporter.so:system/lib/libcrashreporter.so \
    vendor/zte/nx503a/gapps/lib/libfacelock_jni.so:system/lib/libfacelock_jni.so \
    vendor/zte/nx503a/gapps/lib/libfilterframework_jni.so:system/lib/libfilterframework_jni.so \
    vendor/zte/nx503a/gapps/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/zte/nx503a/gapps/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/zte/nx503a/gapps/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp_jni.so \
    vendor/zte/nx503a/gapps/lib/libgcastv2_base.so:system/lib/libgcastv2_base.so \
    vendor/zte/nx503a/gapps/lib/libgcastv2_support.so:system/lib/libgcastv2_support.so \
    vendor/zte/nx503a/gapps/lib/libgoogle_hotword_jni.so:system/lib/libgoogle_hotword_jni.so \
    vendor/zte/nx503a/gapps/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
    vendor/zte/nx503a/gapps/lib/libjgcastservice.so:system/lib/libjgcastservice.so \
    vendor/zte/nx503a/gapps/lib/libjni_unbundled_latinimegoogle.so:system/lib/libjni_unbundled_latinimegoogle.so \
    vendor/zte/nx503a/gapps/lib/libmoviemaker-jni.so:system/lib/libmoviemaker-jni.so \
    vendor/zte/nx503a/gapps/lib/libnetjni.so:system/lib/libnetjni.so \
    vendor/zte/nx503a/gapps/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
    vendor/zte/nx503a/gapps/lib/libpatts_engine_jni_api_ub.210030011.so:system/lib/libpatts_engine_jni_api_ub.210030011.so \
    vendor/zte/nx503a/gapps/lib/libphotoeditor_native.so:system/lib/libphotoeditor_native.so \
    vendor/zte/nx503a/gapps/lib/libplus_jni_v8.so:system/lib/libplus_jni_v8.so \
    vendor/zte/nx503a/gapps/lib/librsjni.so:system/lib/librsjni.so \
    vendor/zte/nx503a/gapps/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    vendor/zte/nx503a/gapps/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    vendor/zte/nx503a/gapps/lib/libvideochat_jni.so:system/lib/libvideochat_jni.so \
    vendor/zte/nx503a/gapps/lib/libwebp_android.so:system/lib/libwebp_android.so \
    vendor/zte/nx503a/gapps/priv-app/ConfigUpdater.apk:system/priv-app/ConfigUpdater.apk \
    vendor/zte/nx503a/gapps/priv-app/GmsCore.apk:system/priv-app/GmsCore.apk \
    vendor/zte/nx503a/gapps/priv-app/GoogleBackupTransport.apk:system/priv-app/GoogleBackupTransport.apk \
    vendor/zte/nx503a/gapps/priv-app/GoogleFeedback.apk:system/priv-app/GoogleFeedback.apk \
    vendor/zte/nx503a/gapps/priv-app/GoogleLoginService.apk:system/priv-app/GoogleLoginService.apk \
    vendor/zte/nx503a/gapps/priv-app/GoogleOneTimeInitializer.apk:system/priv-app/GoogleOneTimeInitializer.apk \
    vendor/zte/nx503a/gapps/priv-app/GooglePartnerSetup.apk:system/priv-app/GooglePartnerSetup.apk \
    vendor/zte/nx503a/gapps/priv-app/GoogleServicesFramework.apk:system/priv-app/GoogleServicesFramework.apk \
    vendor/zte/nx503a/gapps/priv-app/Phonesky.apk:system/priv-app/Phonesky.apk \
    vendor/zte/nx503a/gapps/priv-app/SetupWizard.apk:system/priv-app/SetupWizard.apk \
    vendor/zte/nx503a/gapps/priv-app/Velvet.apk:system/priv-app/Velvet.apk \
    vendor/zte/nx503a/gapps/priv-app/talkback.apk:system/priv-app/talkback.apk \
    vendor/zte/nx503a/gapps/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    vendor/zte/nx503a/gapps/usr/srec/en-US/clg:system/usr/srec/en-US/clg \
    vendor/zte/nx503a/gapps/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf \
    vendor/zte/nx503a/gapps/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    vendor/zte/nx503a/gapps/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    vendor/zte/nx503a/gapps/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    vendor/zte/nx503a/gapps/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    vendor/zte/nx503a/gapps/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn \
    vendor/zte/nx503a/gapps/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    vendor/zte/nx503a/gapps/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    vendor/zte/nx503a/gapps/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model \
    vendor/zte/nx503a/gapps/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    vendor/zte/nx503a/gapps/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    vendor/zte/nx503a/gapps/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword \
    vendor/zte/nx503a/gapps/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols \
    vendor/zte/nx503a/gapps/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist \
    vendor/zte/nx503a/gapps/usr/srec/en-US/hotword.config:system/usr/srec/en-US/hotword.config \
    vendor/zte/nx503a/gapps/usr/srec/en-US/hotword_classifier:system/usr/srec/en-US/hotword_classifier \
    vendor/zte/nx503a/gapps/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer \
    vendor/zte/nx503a/gapps/usr/srec/en-US/hotword_prompt.txt:system/usr/srec/en-US/hotword_prompt.txt \
    vendor/zte/nx503a/gapps/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols \
    vendor/zte/nx503a/gapps/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    vendor/zte/nx503a/gapps/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
    vendor/zte/nx503a/gapps/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer \
    vendor/zte/nx503a/gapps/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer \
    vendor/zte/nx503a/gapps/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map \
    vendor/zte/nx503a/gapps/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    vendor/zte/nx503a/gapps/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm \
    vendor/zte/nx503a/gapps/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist \
    vendor/zte/nx503a/gapps/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin \
    vendor/zte/nx503a/gapps/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin \
    vendor/zte/nx503a/gapps/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin \
    vendor/zte/nx503a/gapps/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin \
    vendor/zte/nx503a/gapps/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin \
    vendor/zte/nx503a/gapps/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin \
    vendor/zte/nx503a/gapps/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin
